version: "3.8"
services:
  web:
    container_name: web
    build:
      context: ./
    ports:
      - "5050:5000"
    environment:
      GREETINGS: "Hello Rubiko Tech!"
    networks:
      - my_network
  curl:
    depends_on:
      - web
    image: curlimages/curl
    command:
      [
        "sh",
        "-c",
        "until curl -s http://web:5000/health; do echo 'Waiting for web service...'; sleep 2; done",
      ]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
